[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mialibreria"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy", "pandas", "matplotlib"]

[tool.hatch.build.targets.wheel]
packages = ["src/mialibreria"]
